name: BookTownControl
version: '${project.version}'
main: gr.btc.BookTownControl
api-version: '1.20'

commands:
  country:
    description: Country removing
  amendlaws:
    description: Change laws of this country
  laws:
    description: Посмотреть какие законы в стране которой вы сейчас находитесь
  tinvite:
    description: Лёгкое приглашение в страну
  menu:
    description: Menu
  army:
    description: Menu
  openbookinmainhand:
    description: Menu